#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    # Register Ghostty as an option for ubuntu default terminal
    update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/bin/ghostty 50
fi

exit 0
