name: Release Zig for PPA

on:
  workflow_dispatch:
    inputs:
      upload:
        description: 'Upload to PPA (default: false)'
        required: false
        default: false
        type: boolean
      ppa:
        description: Target PPA for upload
        required: true
        default: mkasberg/ghostty-ubuntu-nightly
        type: choice
        options:
          - mkasberg/ghostty-ubuntu-nightly
          - mkasberg/ghostty-ubuntu

jobs:
  build-zig:
    name: Build Zig for PPA
    uses: ./.github/workflows/ppa-build-zig.yml
    secrets: inherit
    with:
      upload: ${{ inputs.upload }}
      ppa: ${{ inputs.ppa_name }}
      build_matrix: |
        {
          "builds": [
            {"codename": "noble", "container-image": "ubuntu:24.04"},
            {"codename": "questing", "container-image": "ubuntu:25.10"}
          ]
        }
