name: Test

on:
  pull_request:
  workflow_dispatch:

concurrency:
  # Repeated pushes to a PR will cancel all previous still running builds of the
  # PR (for faster feedback)
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-zig-ppa:
    name: PPA Zig
    uses: ./.github/workflows/ppa-build-zig.yml
    with:
      upload: false
      build_matrix: |
        {
          "builds": [
            {"codename": "questing", "container-image": "ubuntu:25.10"}
          ]
        }

  build-ghostty-ppa:
    name: PPA Ghostty
    uses: ./.github/workflows/ppa-build-ghostty.yml
    with:
      upload: false
      version: '1.3.1'
      build_matrix: |
        {
          "builds": [
            {"codename": "questing", "container-image": "ubuntu:25.10"}
          ]
        }
